using System;
using System.Collections.Generic;

namespace MediClinic.Models.EntityModels
{
    public partial class ReportExamInformation
    {
        public int ExamInformationId { get; set; }
        public DateTime DateOfExam { get; set; }
        public bool IsNumbnessTingling { get; set; }
        public string NumbnessTingling { get; set; }
        public bool IsSwelling { get; set; }
        public string Swelling { get; set; }
        public bool IsPain { get; set; }
        public string Pain { get; set; }
        public bool IsWeakness { get; set; }
        public string Weakness { get; set; }
        public bool IsStiffness { get; set; }
        public string Stiffness { get; set; }
        public bool IsOtherSpecify { get; set; }
        public string OtherSpecify { get; set; }
        public bool IsAbrasion { get; set; }
        public string Abrasion { get; set; }
        public bool IsInfectiousDisease { get; set; }
        public string InfectiousDisease { get; set; }
        public bool IsAmputation { get; set; }
        public string Amputation { get; set; }
        public bool IsInhalationExposure { get; set; }
        public string InhalationExposure { get; set; }
        public bool IsAvulsion { get; set; }
        public string Avulsion { get; set; }
        public bool IsLaceration { get; set; }
        public string Laceration { get; set; }
        public bool IsBite { get; set; }
        public string Bite { get; set; }
        public bool IsNeedleStick { get; set; }
        public string NeedleStick { get; set; }
        public bool IsBurn { get; set; }
        public string Burn { get; set; }
        public bool IsPoisoningToxicEffects { get; set; }
        public string PoisoningToxicEffects { get; set; }
        public bool IsContusionHematoma { get; set; }
        public string ContusionHematoma { get; set; }
        public bool IsPsychological { get; set; }
        public string Psychological { get; set; }
        public bool IsCrushInjury { get; set; }
        public string CrushInjury { get; set; }
        public bool IsPunctureWound { get; set; }
        public string PunctureWound { get; set; }
        public bool IsDermatitis { get; set; }
        public string Dermatitis { get; set; }
        public bool IsRepetitiveStrainInjury { get; set; }
        public string RepetitiveStrainInjury { get; set; }
        public bool IsDislocation { get; set; }
        public string Dislocation { get; set; }
        public bool IsSpinalCordInjury { get; set; }
        public string SpinalCordInjury { get; set; }
        public bool IsFracture { get; set; }
        public string Fracture { get; set; }
        public bool IsSprainStrain { get; set; }
        public string SprainStrain { get; set; }
        public bool IsHearingLoss { get; set; }
        public string HearingLoss { get; set; }
        public bool IsTornLigamentTendonMuscle { get; set; }
        public string TornLigamentTendonMuscle { get; set; }
        public bool IsHernia { get; set; }
        public string Hernia { get; set; }
        public bool IsVisionLoss { get; set; }
        public string VisionLoss { get; set; }
        public string FullName { get; set; }
        public DateTime DateOfInjury { get; set; }
        public bool IsNoneAtPresent { get; set; }
        public bool IsBruising { get; set; }
        public string Bruising { get; set; }
        public bool IsNeuromuscular { get; set; }
        public string Burns { get; set; }
        public bool IsBurns { get; set; }
        public bool IsAbnormal { get; set; }
        public bool IsCrepitation { get; set; }
        public string Crepitation { get; set; }
        public bool IsActiveROM { get; set; }
        public string ActiveROM { get; set; }
        public bool IsDeformity { get; set; }
        public string Deformity { get; set; }
        public bool IsPassiveROM { get; set; }
        public string PassiveROM { get; set; }
        public bool IsEdema { get; set; }
        public string Edema { get; set; }
        public bool IsGait { get; set; }
        public string Gait { get; set; }
        public bool IsHematomaLumpSwelling { get; set; }
        public string HematomaLumpSwelling { get; set; }
        public bool IsPalpableMuscleSpasm { get; set; }
        public string PalpableMuscleSpasm { get; set; }
        public bool IsJointEffusion { get; set; }
        public string JointEffusion { get; set; }
        public bool IsReflexes { get; set; }
        public string Reflexes { get; set; }
        public bool IsLacerationSutures { get; set; }
        public string LacerationSutures { get; set; }
        public bool IsSensation { get; set; }
        public string Sensation { get; set; }
        public bool IsScar { get; set; }
        public string Scar { get; set; }
        public bool IsWastingMuscleAtrophy { get; set; }
        public string WastingMuscleAtrophy { get; set; }
        public bool IsOtherFindings { get; set; }
        public string OtherFindings { get; set; }
        public string AnyDiagnosticTest { get; set; }
        public string AnyTreatment { get; set; }
        public string PrognosisForRecovery { get; set; }
        public bool IsAnyPreexistingCondition { get; set; }
        public int VisitId { get; set; }
        public bool? IsOtheinjury { get; set; }
        public string OtherInjury { get; set; }
        public long? PatientId { get; set; }

        public virtual PatientInfo Patient { get; set; }
    }
}
